# Generated by Django 4.2.25 on 2025-10-22 22:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id_hospital', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('camas_totales', models.IntegerField(default=0)),
                ('camas_ocupadas', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'HOSPITAL',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=50, null=True)),
                ('prevision', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'PACIENTE',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('clave', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('TENS', 'TENS'), ('Médico', 'Médico'), ('Coordinador', 'Coordinador')], max_length=20)),
            ],
            options={
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='FichaPaciente',
            fields=[
                ('id_ficha', models.AutoField(primary_key=True, serialize=False)),
                ('comorbilidades', models.TextField(blank=True, null=True)),
                ('funcionalidad', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_paciente', models.OneToOneField(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, to='hospital.paciente')),
            ],
            options={
                'db_table': 'FICHA_PACIENTE',
            },
        ),
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id_derivacion', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('prestacion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('En revisión', 'En revisión')], default='Pendiente', max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_hospital', models.ForeignKey(db_column='id_hospital', on_delete=django.db.models.deletion.RESTRICT, to='hospital.hospital')),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.RESTRICT, to='hospital.paciente')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, to='hospital.usuario')),
            ],
            options={
                'db_table': 'DERIVACION',
            },
        ),
    ]
