# Generated by Django 4.2.25 on 2025-10-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='comorbilidades',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='funcionalidad',
            field=models.CharField(blank=True, choices=[('Autovalente', 'Autovalente'), ('Dependencia Leve', 'Dependencia Leve'), ('Dependencia Severa', 'Dependencia Severa')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='prevision',
            field=models.CharField(blank=True, choices=[('Fonasa', 'Fonasa'), ('Isapre', 'Isapre'), ('Particular', 'Particular')], max_length=20, null=True),
        ),
    ]
